### ISSUE TITLE
subroutes

### ISSUE THREAD

**Issue by pierluc-codes** [juanmnl/react-starter#1]
I was playing with a personal project and trying to integrate react-router

I have the following routes:

main page: /account
subpage: /account/:accountId 

When I go to the subpage everything is fine.

But if I refresh the subpag, it cannot load bundle.js! Because it tries to 
`GET http://localhost:8080/accounts/bundle.js`
and it does not exists.

I changed bundle.js for /bundle.js

`<script src="/bundle.js" charset="utf-8"></script>
`
But i got the following error when bootstrap is loading it's css. It tries to load
`addStyleUrl.js?796a:15 GET http://localhost:8080/accounts/2f624089c65f12185e79925bc5a7fc42.css`
and it does not exists

Any idea how what is the good fix?

**Comment by juanmnl** [comment]
That's weird, i guess there's a problem with the config –as you shouldn't need to change the paths to the bundle or the css. Is there a repo where i can take a look?

**Comment by juanmnl** [comment]
[Here you have](https://github.com/reactjs/react-router/blob/master/docs/guides/RouteConfiguration.md) the best tutorial on how to config routes and nested routes, but let me know if you can't find a fix.  
:)

**Comment by juanmnl** [comment]
I think i found the problem your getting into. It's well explained [in this article.](https://css-tricks.com/learning-react-router/#article-header-id-9)

**Comment by pierluc-codes** [comment]
i found a solution with this

http://stackoverflow.com/questions/26203725/how-to-allow-for-webpack-dev-server-to-allow-entry-points-from-react-router

**Comment by pierluc-codes** [comment]
I think it could be useful if you intergrate with it. But I understand that it will add complexity.

**Comment by juanmnl** [comment]
That's a great idea @plcstpierre but maybe not for the main starter. I could try and make an alternative install (a branch) with express and a routing demo.
Thanks for the link.
